name: Morales Bot - Build and Publish APK

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  android:
    uses: pgsilva/deck-actions/.github/workflows/android-ci-cd.yml@main
    with:
      secrets: inherit